version: '3'

networks:
  kong-net:
    driver: bridge

services:
  kong-db:
    image: postgres:9.6
    restart: always
    networks:
      - kong-net
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: kong
      POSTGRES_USER: kong
      # POSTGRES_PASSWORD: SHUNTeRTosTOneDw
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "kong"]
      interval: 5s
      timeout: 5s
      retries: 5

  #######################################
  # Kong database migration
  #######################################
  kong-migration:
    image: kong:1.4
    command: "kong migrations bootstrap"
    networks:
      - kong-net
    restart: on-failure
    environment:
      KONG_PG_HOST: kong-db
    depends_on:
      - kong-db

  kong:
    image: kong:1.4
    restart: on-failure
    networks:
      - kong-net
    depends_on:
      - kong-migration
      - kong-db
    ports:
      - 8000:8000
      - 8001:8001
    environment:
      - KONG_DATABASE=postgres
      - KONG_PG_HOST=kong-db
      # - KONG_PG_PASSWORD=SHUNTeRTosTOneDw
      - KONG_PROXY_LISTEN=0.0.0.0:8000
      - KONG_ADMIN_LISTEN=0.0.0.0:8001
      - KONG_ADMIN_ACCESS_LOG='/dev/stdout'
      - KONG_ADMIN_ERROR_LOG='/dev/stderr'
      - KONG_PROXY_ACCESS_LOG='/dev/stdout'
      - KONG_PROXY_ERROR_LOG='/dev/stderr'

  #######################################
  # Konga database prepare
  #######################################
  konga-prepare:
    image: pantsel/konga:0.14.7
    command: "-c prepare -a postgres -u postgresql://kong@kong-db:5432/konga_db"
    networks:
      - kong-net
    restart: on-failure
    depends_on:
      - kong-db

  #######################################
  # Konga: Kong GUI
  #######################################
  konga:
    image: pantsel/konga:0.14.7
    restart: always
    networks:
        - kong-net
    environment:
      KONGA_HOOK_TIMEOUT: 60000
      DB_ADAPTER: postgres
      DB_HOST: kong-db
      DB_USER: kong
      TOKEN_SECRET: km9GUr4RkcQD7DewhJPNXrCuZwcKmqjb
      DB_DATABASE: konga_db
      NODE_ENV: production
    depends_on:
      - kong-db
    ports:
      - "1337:1337"
