global:
  scrape_interval: 10s
  evaluation_interval: 15s
scrape_configs:
  - job_name: 'esop-tracing'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['host.docker.internal:9091']
  - job_name: 'margin-module'
    metrics_path: /margin-module/prometheus
    static_configs:
      - targets: ['host.docker.internal:9091']
