version: '2'
services:
  kong-db:
    image: postgres:9.6
    environment:
      POSTGRES_DB: kong
      POSTGRES_USER: kong
      POSTGRES_PASSWORD: SHUNTeRTosTOneDw

  kong:
    image: kong:0.14.1
    restart: on-failure
    command: 'kong start --run-migrations'
    depends_on:
      - kong-db
    ports:
      - 8000:8000
      - 8443:8443
      - 8001:8001
      - 7946:7946
      - 7946:7946/udp
    environment:
      - KONG_DATABASE=postgres
      - KONG_PG_HOST=kong-db
      - KONG_PG_PASSWORD=SHUNTeRTosTOneDw
      - KONG_ADMIN_LISTEN=0.0.0.0:8001
      - KONG_ADMIN_ACCESS_LOG='/dev/stdout'
      - KONG_ADMIN_ERROR_LOG='/dev/stderr'
      - KONG_PROXY_ACCESS_LOG='/dev/stdout'
      - KONG_PROXY_ERROR_LOG='/dev/stderr'
  konga:
    image: pantsel/konga:0.11.2
    restart: on-failure
    depends_on:
      - kong
      - mongo
    environment:
      - NODE_ENV=production
      - DB_ADAPTER=mongo
      - DB_HOST=mongo
      - DB_PORT=27017
    ports:
      - '8081:1337'
  mongo:
    image: mongo:3.6
    volumes:
      - './data:/data/db'


